name: C/C++ CI

on:
  push:
    branches: [ master, OPC-UA ]
  pull_request:
    branches: [ master, OPC-UA ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '9-2019-q4' # The arm-none-eabi-gcc release to use.       
    - name: make      
      run: make -C devices/remote_io/software
